version: "3.8"
services:

  kafka1:
    image: vinsdocker/kafka
    container_name: kafka1
    ports:
    - "8081:8081"
    environment:
      - KAFKA_CLUSTER_ID=OTMwNzFhYTY10DNiNGE50T
    volumes:
    - ./props/s1.properties:/kafka/config/kraft/server.properties
    - ./data/d1/:/tmp/kafka-logs
  
  kafka2:
    image: vinsdocker/kafka
    container_name: kafka2
    ports:
    - "8082:8082"
    environment:
      - KAFKA_CLUSTER_ID=OTMwNzFhYTY10DNiNGE50T
    volumes:
    - ./props/s2.properties:/kafka/config/kraft/server.properties
    - ./data/d2/:/tmp/kafka-logs
  
  kafka3:
    image: vinsdocker/kafka
    container_name: kafka3
    ports:
    - "8083:8083"
    environment:
      - KAFKA_CLUSTER_ID=OTMwNzFhYTY10DNiNGE50T
    volumes:
    - ./props/s3.properties:/kafka/config/kraft/server.properties
    - ./data/d3/:/tmp/kafka-logs